steps:
- task: cmd
  inputs:
    script: 
      - echo "number 1 hello"

- task: cmd
  inputs:
    script: 
      - echo "number 2 hello"


# - task: testing
#   inputs:
#     version: v1.0.1



# - task: docker
#   inputs:
#     command: build
#     context:
#     dockerfile:
#     repository:
#     tags:
#     arguments: