image: alpine:latest

stages:
  - prepare
  - build
  - release
  - post

include:
  - remote: 'https://github.com/purwandi/zepline-test.git'
    credential: github-credentials
    ref: main
    files: 
      - /helm.yaml

tasks:
  # release:
  #   image: alpine:3.13
  #   stage: release
  #   script: 
  #     - echo "hello from alpine 3.13"
  #     - sleep 10

  # notification:
  #   image: alpine
  #   stage: prepare
  #   script:
  #     - echo "hello notification"
  #     - sleep 15

  # docker:
  #   image: alpine
  #   stage: build
  #   services:
  #     - image: nginx:alpine
  #       alias: web
  #       # entrypoint: 
  #       # command: 
  #   script:
  #     - echo "hello"
  #     - sleep 7

  helm:
    image: alpine
    extends: .helm
    credentials:
      - credential: github-credentials
        type: usernamePassword
        variables:
          username: GITHUB_USERNAME
          password: GITHUB_PASSWORD
      # - credential: github-credentials
      #   type: usernameColonPassword
      #   variables:
      #     variable: GITHUB_TOKEN
      # - credential: file-secret
      #   type: file
      #   variables:
      #     variable: FILE_SECRET
      # - credential: secret-text
      #   type: string
      #   variables:
      #     variable: FILE_SECRET
    stage: build
    services:
      - image: nginx:alpine
        alias: web
        # entrypoint: 
        # command: 
    # script:
    #   - echo "hello"
    #   - sleep 10

  # helm:
  #   extends: .helm
  #   stage: release
  #   variables:
  #     ENV: prod