stages:
  - pre
  - build

include:
  - remote: https://gitlab.com/optimus-openshift/jenkins/jenkins-pipeline.git
    credential: gitlab-credentials
    ref: main
    files:
      - /variables.yaml
      - /nodejs.yaml

tasks:
  notification:
    image: docker.io/alpine:3.13
    stage: pre
    script:
      - echo "Prepare for deployment"

  kaniko:
    image: ghcr.io/purwandi/zepline:kaniko
    stage: build
    script:
      - echo "build kaniko"