image: alpine:latest

include:
  - receipt: 'https://gitlab.com/purwandi/zepline-pipeline.git'
    credential: github-credentials
    ref: main
    file: 
      - /variables.yaml
      - /pre-post.yaml
      - /helm.yaml

services:
  - image: docker:dind
  - image: postgres:alpine

environment:

steps:
- task: cmd
  input:
    script: 
      - echo "number 1 hello"
      - echo "number 2 hello"
      - env

- task: cmd
  input:
    script:
      - | 
        echo "number 2 hello"
        env
      - echo "Hello world"

- task: docker
  image: docker:latest
  input:
    context: $WORKSPACE
    dockerfile: $WORKSPACE/Dockerfile
    credential: github-credentials
    registry: https://ghcr.io
    command: buildPush
    repository: ghcr.io/purwandi/zepline
    tag: dev-9898
    args: "--build-arg token=x887232"

# - task: helm
#   image: dtzar/helm-kubectl
#   input:
#     script:
#       - kubectl version --short || true
#       - helm version --short || true

# - task: testing
#   input:
#     version: v1.0.1



# - task: docker
#   input:
#     command: build
#     context:
#     dockerfile:
#     repository:
#     tags:
#     arguments: