stages:
  - pre
  - build

include:
  - remote: https://gitlab.com/optimus-openshift/jenkins/jenkins-pipeline.git
    credential: gitlab-credentials
    ref: main
    files:
      - /variables.yaml
      - /kaniko.yaml
      - /nodejs.yaml

tasks:
  notification:
    image: docker.io/alpine:3.13
    stage: pre
    script:
      - echo "Prepare for deployment"

  kaniko:
    extend: .kaniko
    stage: build
    variables:
      CI_PROJECT_PATH: purwandi/zepline
    script: 
      - env