image: 

services:
- docker:dind
- postgres:alpine

environment:

steps:
- task: cmd
  input:
    script: 
      - echo "number 1 hello"
      - echo "number 2 hello"
      - env

- task: cmd
  input:
    script:
      - | 
        echo "number 2 hello"
        env
      - echo "Hello world"

- task: docker
  input:
    context: $WORKSPACE
    dockerfile: $WORKSPACE/Dockerfile
    credential: github-credentials
    registry: https://ghcr.io
    command: buildPush
    repository: ghcr.io/purwandi/zepline
    tag: dev-9898
    args: "--build-arg token=x887232"

# - task: testing
#   input:
#     version: v1.0.1



# - task: docker
#   input:
#     command: build
#     context:
#     dockerfile:
#     repository:
#     tags:
#     arguments: