stages:
  - pre
  - build

include:
  - remote: https://gitlab.com/optimus-openshift/jenkins/jenkins-pipeline.git
    credential: gitlab-credentials
    ref: main
    files:
      - /variables.yaml
      - /nodejs.yaml

tasks:
  notification:
    image: docker.io/alpine:3.13
    stage: pre
    script:
      - echo "Prepare for deployment"

  kaniko:
    image:
      name: ghcr.io/purwandi/zepline:kaniko
      args: -u 0
    stage: build
    variables:
      DOCKER_HOSTED: ghcr.io
    credentials:
      - credential: github-credentials
        type: usernamePassword
        variables:
          username: GITHUB_USERNAME
          password: GITHUB_PASSWORD
    before_script:
      - /kaniko/helper auth:docker --username $GITHUB_USERNAME --password $GITHUB_PASSWORD --registry $DOCKER_HOSTED
    script:
      - echo "build kaniko"
      - echo $DOCKER_HOSTED
      - /kaniko/executor
          --context $WORKSPACE
          --dockerfile $WORKSPACE/Dockerfile
          --destination $DOCKER_HOSTED/purwandi/zepline:$CI_GIT_COMMIT_SHORT_SHA
      - executor --context /workspace --dockerfile /workspace/Dockerfile --destination ghcr.io/purwandi/zepline:debug