image: alpine:latest

include:
  - remote: 'https://gitlab.com/purwandi/zepline-test.git'
    credential: github-credentials
    ref: docker-runner
    files: 
      - /helm.yaml

tasks:
  release:
    image: alpine:3.13
    stage: release
    script: 
      - echo "hello from alpine 3.13"
      - sleep 10

  helm:
    extends: .helm
    stage: release
    variables:
      ENV: prod