image: 

services:
- docker:dind
- postgres:alpine

environment:

steps:
- task: cmd
  inputs:
    script: 
      - echo "number 1 hello"
      - echo "number 2 hello"
      - env

# - task: ssh
#   inputs:
#     credentials: ssh-server-10
#     script:
#       - echo "hello"

- task: cmd
  inputs:
    script: 
      - echo "number 2 hello"

- task: cmd
  inputs:
    script:
      - | 
        echo "number 2 hello"
        env
      - echo "Hello world"

- task: docker
  inputs:
    context: ${WORKSPACE}
    dockerfile: ${WORKSPACE}/Dockerfile
    credential: dockerhub-credentials
    registry: https://index.docker.io/v1/
    command: build
    repository: istio
    tag: dev-9898
    args:

# - task: testing
#   inputs:
#     version: v1.0.1



# - task: docker
#   inputs:
#     command: build
#     context:
#     dockerfile:
#     repository:
#     tags:
#     arguments: