image: 

services:
- docker:dind
- postgres:alpine

environment:

steps:
- task: cmd
  input:
    script: 
      - echo "number 1 hello"
      - echo "number 2 hello"
      - env

# - task: ssh
#   input:
#     credentials: ssh-server-10
#     script:
#       - echo "hello"

- task: cmd
  input:
    script: 
      - echo "number 2 hello"

- task: cmd
  input:
    script:
      - | 
        echo "number 2 hello"
        env
      - echo "Hello world"

- task: docker
  input:
    context: ${WORKSPACE}
    dockerfile: ${WORKSPACE}/Dockerfile
    credential: github-credentials
    registry: ghcr.io
    command: build
    repository: purwandi/zepline
    tag: dev-9898
    args:

# - task: testing
#   input:
#     version: v1.0.1



# - task: docker
#   input:
#     command: build
#     context:
#     dockerfile:
#     repository:
#     tags:
#     arguments: