version: '3'

services:
  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - ./storage-jenkins:/var/jenkins_home
      - ./storage-docker:/certs/client

  jenkins:
    image: jenkinsci/blueocean:1.24.7
    container_name: jenkins
    privileged: true
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - ./storage-jenkins:/var/jenkins_home
      - ./storage-docker:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
