stages:
  - prepare
  - build
  - release
  - post

tasks:
  release:
    image: alpine:3.13
    stage: release
    script: 
      - echo "hello from alpine 3.13"
      - sleep 10

  notification:
    image: alpine
    stage: prepare
    script:
      - echo "hello notification"
      - sleep 15

  test:
    image: alpine
    stage: build
    services:
      - image: nginx:alpine
        alias: web
        # entrypoint: 
        # command: 
    script:
      - echo "hello"
      - sleep 7

  docker:
    image: alpine:3.13
    stage: build
    script: 
      - echo "hello from alpine 3.13"
      - sleep 20

  helm:
    extends: .helm
    stage: release
    variables:
      ENV: prod
  
  notif_post:
    image: alpine:3.13
    stage: post
    script: 
      - echo "post from alpine 3.13"
      - sleep 20